// 应用常量

// Action类型
export const ActionTypes = {
  // 用户相关
  SET_USER_DATA: 'SET_USER_DATA',
  COMPLETE_SETUP: 'COMPLETE_SETUP',
  UPDATE_USER_PREFERENCES: 'UPDATE_USER_PREFERENCES',

  // 餐厅相关
  SET_RESTAURANTS: 'SET_RESTAURANTS',
  ADD_RESTAURANT: 'ADD_RESTAURANT',
  UPDATE_RESTAURANT: 'UPDATE_RESTAURANT',
  DELETE_RESTAURANT: 'DELETE_RESTAURANT',

  // 选择流程
  SET_FLOW_STEP: 'SET_FLOW_STEP',
  SET_SELECTED_MEAL_TYPE: 'SET_SELECTED_MEAL_TYPE',
  SET_SELECTED_RESTAURANT: 'SET_SELECTED_RESTAURANT',
  SET_RESELECTION_STEP: 'SET_RESELECTION_STEP',
  SET_RESELECTION_OPTIONS: 'SET_RESELECTION_OPTIONS',
  ADD_SHOWN_RESTAURANT: 'ADD_SHOWN_RESTAURANT',
  RESET_SELECTION_FLOW: 'RESET_SELECTION_FLOW',

  // 反馈相关
  SET_PENDING_FEEDBACK: 'SET_PENDING_FEEDBACK',
  CLEAR_PENDING_FEEDBACK: 'CLEAR_PENDING_FEEDBACK',

  // UI状态
  SET_LOADING: 'SET_LOADING',
  SET_SHOW_FEEDBACK: 'SET_SHOW_FEEDBACK',
  SET_SHOW_MENU: 'SET_SHOW_MENU',

  // 营养分析相关
  SET_NUTRITION_DATA: 'SET_NUTRITION_DATA',
  CLEAR_NUTRITION_DATA: 'CLEAR_NUTRITION_DATA',
  SET_FOOD_DESCRIPTION: 'SET_FOOD_DESCRIPTION',

  // 营养目标相关
  SET_NUTRITION_GOAL: 'SET_NUTRITION_GOAL',
  CLEAR_NUTRITION_GOAL: 'CLEAR_NUTRITION_GOAL'
};