# Netlify 配置文件
# 用于配置构建设置和Serverless Functions

[build]
  # 构建命令
  command = "npm run build"

  # 构建输出目录
  publish = "dist"

  # Functions 目录
  functions = "netlify/functions"

# 本地开发服务器配置
[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = false

# 环境变量（生产环境需要在Netlify Dashboard配置）
# GEMINI_API_KEY = "your_api_key_here"

# 重定向规则（单页应用路由支持）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Functions 配置
[functions]
  # Functions 目录
  directory = "netlify/functions"

  # Node.js 版本
  node_bundler = "esbuild"
